{
 "title": "Teku Monitor",
 "description": "Dashboard Teku Beacon Chain Nodes",
 "tags": [
  "ethereum",
  "teku",
  "eth2.0"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "system", "label": "System", "query": "beacon_slot" }
  ]
 },
 "panels": [
  {
   "title": "Stats",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (instance) (beacon_slot{instance=~\"$system\"})",
     "legendFormat": "Beacon Slot"
    },
    {
     "expr": "sum by (instance) (beacon_head_slot{instance=~\"$system\"})",
     "legendFormat": "Head Slot"
    },
    {
     "expr": "sum by (instance) (beacon_epoch{instance=~\"$system\"})"
    },
    {
     "expr": "sum by (instance) (beacon_current_justified_epoch{instance=~\"$system\"})"
    },
    {
     "expr": "sum by (instance) (beacon_finalized_epoch{instance=~\"$system\"})"
    },
    {
     "expr": "sum by (instance) (validator_local_validator_count{instance=~\"$system\"})"
    },
    {
     "expr": "sum by (instance) (validator_beacon_node_published_block_total{instance=~\"$system\"})"
    },
    {
     "expr": "sum by (instance) (validator_beacon_node_published_attestation_total{instance=~\"$system\"})"
    },
    {
     "expr": "sum by (instance) (validator_beacon_node_published_aggregate_total{instance=~\"$system\"})"
    },
    {
     "expr": "sum by (instance) (libp2p_peers{instance=~\"$system\"})"
    },
    {
     "expr": "sum by (instance) (beacon_previous_live_validators{instance=~\"$system\"})"
    },
    {
     "expr": "sum by (instance) (beacon_previous_live_validators{instance=~\"$system\"} /  beacon_previous_active_validators{instance=~\"$system\"})"
    }
   ]
  },
  { "title": "Stats $system", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "system" },
  {
   "title": "Beacon Chain",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "beacon_slot{instance=~\"$system\"}",
     "legendFormat": "Current Slot"
    },
    {
     "expr": "beacon_head_slot{instance=~\"$system\"}",
     "legendFormat": "Head Block Slot"
    },
    {
     "expr": "beacon_epoch{instance=~\"$system\"}",
     "legendFormat": "Current Epoch"
    },
    {
     "expr": "beacon_current_justified_epoch{instance=~\"$system\"}",
     "legendFormat": "Justified Epoch"
    },
    {
     "expr": "beacon_finalized_epoch{instance=~\"$system\"}",
     "legendFormat": "Finalised Epoch"
    }
   ]
  },
  {
   "title": "Validator Client",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 9 },
   "targets": [
    {
     "expr": "validator_local_validator_count{instance=~\"$system\"}",
     "legendFormat": "Local Validators"
    },
    {
     "expr": "validator_beacon_node_published_block_total{instance=~\"$system\"}",
     "legendFormat": "Published Blocks"
    },
    {
     "expr": "validator_beacon_node_published_attestation_total{instance=~\"$system\"}",
     "legendFormat": "Published Attestations"
    },
    {
     "expr": "validator_beacon_node_published_aggregate_total{instance=~\"$system\"}",
     "legendFormat": "Published Aggregates"
    }
   ]
  },
  {
   "title": "Network",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 9 },
   "targets": [
    {
     "expr": "libp2p_peers{instance=~\"$system\"}",
     "legendFormat": "Peer Count"
    },
    {
     "expr": "network_peer_goodbye_total{instance=~\"$system\"}",
     "legendFormat": "Disconnected ({{reason}})"
    }
   ]
  },
  {
   "title": "Live Validators (Previous Epoch)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 15, "y": 9 },
   "targets": [
    {
     "expr": "beacon_previous_live_validators{instance=~\"$system\"} /  beacon_previous_active_validators{instance=~\"$system\"}"
    }
   ]
  },
  {
   "title": "Live Validators (Current Epoch)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 19, "y": 9 },
   "targets": [
    {
     "expr": "beacon_current_live_validators{instance=~\"$system\"} /  beacon_current_active_validators{instance=~\"$system\"}"
    }
   ]
  },
  { "title": "Validator Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Validators",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " beacon_previous_active_validators{instance=~\"$system\"}",
     "legendFormat": " {{instance}} Previous Active Validators"
    },
    {
     "expr": "beacon_previous_live_validators{instance=~\"$system\"}",
     "legendFormat": "{{instance}} Previous Live Validators"
    }
   ]
  },
  {
   "title": "Participation Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "beacon_previous_live_validators{instance=~\"$system\"} / beacon_previous_active_validators{instance=~\"$system\"}",
     "legendFormat": "{{instance}} Participation Rate (Previous Epoch)"
    },
    { "expr": "0.66666666667", "legendFormat": "Finalization" }
   ]
  },
  {
   "title": "Pending Duties",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "validator_scheduled_duties_current{instance=~\"$system\"}",
     "legendFormat": "{{instance}} Pending Duties"
    }
   ]
  },
  {
   "title": "Beacon Node Requests per Hour",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(validator_beacon_node_unsigned_attestation_requests_total{instance=~\"$system\"}[1h])*60*60",
     "legendFormat": "{{instance}} Create Attestation {{outcome}}"
    },
    {
     "expr": "rate(validator_beacon_node_aggregate_requests_total{instance=~\"$system\"}[1h])*60*60",
     "legendFormat": "{{instance}} Create Aggregate {{outcome}}"
    },
    {
     "expr": "rate(validator_beacon_node_unsigned_block_requests_total{instance=~\"$system\"}[1h])*60*60",
     "legendFormat": "{{instance}} Create Block {{outcome}}"
    },
    {
     "expr": "rate(validator_beacon_node_duties_requests_total{instance=~\"$system\"}[1h])*60*60",
     "legendFormat": "{{instance}} Duties {{outcome}}"
    }
   ]
  },
  { "title": "Beacon Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Epoch",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "beacon_epoch{instance=~\"$system\"} - beacon_finalized_epoch{instance=~\"$system\"} - 2",
     "legendFormat": "{{instance}} Finalization Delay"
    },
    {
     "expr": "beacon_epoch{instance=~\"$system\"} - beacon_current_justified_epoch{instance=~\"$system\"} - 1",
     "legendFormat": "{{instance}} Justification Delay"
    }
   ]
  },
  {
   "title": "Slot",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 52 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "beacon_slot{instance=~\"$system\"} - beacon_head_slot{instance=~\"$system\"}",
     "legendFormat": "{{instance}} Head Slot Trailing Distance"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "graph",
   "description": "The number of peers currently connected.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "libp2p_peers{instance=~\"$system\"}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{instance=~\"$system\"}[1m])",
     "legendFormat": "CPU Time IRate [{{instance}}]"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 62 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{instance=~\"$system\"}",
     "legendFormat": "{{instance}} {{area}}"
    },
    {
     "expr": "sum by (instance) (jvm_memory_bytes_used{instance=~\"$system\"})",
     "legendFormat": "{{instance}} Total"
    },
    {
     "expr": "sum by (instance) (jvm_memory_bytes_max{instance=~\"$system\"})",
     "legendFormat": "{{instance}} Max"
    }
   ]
  },
  {
   "title": "GC time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 62 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{instance=~\"$system\"}[1m])",
     "legendFormat": "{{gc}} [{{instance}}]"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{instance=~\"$system\"}",
     "legendFormat": "{{instance}} {{job}} Open File Descriptor Count"
    }
   ]
  },
  {
   "title": "Process Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\"$system\"}",
     "legendFormat": "{{instance}} {{job}} Resident Memory"
    }
   ]
  },
  {
   "title": "Hot State Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(storage_memory_state_requests{instance=~\"$system\"}[1m])",
     "legendFormat": "{{instance}} {{result}}"
    }
   ]
  },
  {
   "title": "In Memory Storage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "storage_memory_state_count{instance=~\"$system\"}",
     "legendFormat": "{{instance}} States"
    },
    {
     "expr": "storage_memory_block_count{instance=~\"$system\"}",
     "legendFormat": "{{instance}} Blocks"
    },
    {
     "expr": "storage_memory_checkpoint_state_count{instance=~\"$system\"}",
     "legendFormat": "{{instance}} Checkpoint States"
    }
   ]
  }
 ]
}