{
 "title": "Teku Overview (Ben)",
 "description": "Provides an overview of a Teku Ethereum 2.0 node",
 "tags": [
  "ethereum",
  "teku",
  "eth2.0"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   { "name": "system", "label": "System", "query": "query_result(beacon_slot)" }
  ]
 },
 "panels": [
  {
   "title": "Config",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Max heap",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jvm_memory_bytes_max{area=\"heap\"}"
      }
     ]
    },
    {
     "title": "Local Validator Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "validator_local_validator_count"
      }
     ]
    }
   ]
  },
  {
   "title": "Sync",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Synced %",
     "type": "gauge",
     "description": "Proportion of slots that are synced",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 * beacon_head_slot / beacon_slot"
      }
     ]
    },
    {
     "title": "Slots behind",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "beacon_slot - beacon_head_slot" }
     ]
    },
    {
     "title": "Sync rate (slots/s)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "rate (beacon_head_slot[30s])" }
     ]
    },
    {
     "title": "Remaining time",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "clocks" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(beacon_slot - beacon_head_slot) / rate (beacon_head_slot[30s])"
      }
     ]
    }
   ]
  },
  { "title": "Beacon Chain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Slot",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "beacon_slot" }
   ]
  },
  {
   "title": "Epoch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "beacon_epoch" }
   ]
  },
  {
   "title": "Epochs since finalisation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_epoch - beacon_finalized_epoch"
    }
   ]
  },
  {
   "title": "Time since finalisation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "12 * (beacon_slot - 32 * beacon_finalized_epoch)"
    }
   ]
  },
  {
   "title": "Validators",
   "type": "stat",
   "description": "Current active validators (not \"live\")",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_current_active_validators"
    }
   ]
  },
  {
   "title": "Participation",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * beacon_previous_live_validators / beacon_previous_active_validators"
    }
   ]
  },
  { "title": "Teku", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Teku Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{instance=\"localhost:8008\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Peer count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "libp2p_peers" }
   ]
  },
  {
   "title": "JVM Heap Used",
   "type": "gauge",
   "description": "Percentage of the java heap used",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * jvm_memory_bytes_used{instance=~\"$system\", area=\"heap\"} / jvm_memory_bytes_max{instance=~\"$system\", area=\"heap\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Young GC time",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{instance=~\"$system\",gc=\"G1 Young Generation\"}[1m])",
     "legendFormat": "{{gc}} [{{instance}}]"
    }
   ]
  },
  {
   "title": "Old GC time",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{instance=~\"$system\",gc=\"G1 Old Generation\"}[1m])",
     "legendFormat": "{{gc}} [{{instance}}]"
    }
   ]
  },
  {
   "title": "Data FS Used",
   "type": "gauge",
   "description": "Used Data FS",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/data\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/data\"})"
    }
   ]
  },
  { "title": "Beacon Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Slot",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "beacon_slot" },
    { "expr": "beacon_head_slot" }
   ]
  },
  {
   "title": "Epoch",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "beacon_epoch" },
    { "expr": "beacon_current_justified_epoch" },
    {
     "expr": "beacon_previous_justified_epoch"
    },
    { "expr": "beacon_finalized_epoch" }
   ]
  },
  {
   "title": "Peers",
   "type": "graph",
   "description": "The number of peers currently connected.",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "libp2p_peers" }
   ]
  },
  {
   "title": "Validators",
   "type": "graph",
   "description": "Active and live validators based on the previous epoch",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "beacon_previous_live_validators",
     "legendFormat": "Live"
    },
    {
     "expr": "beacon_previous_active_validators",
     "legendFormat": "Active"
    },
    { "legendFormat": "Threshold" }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{instance=~\"$system\"}[1m])",
     "legendFormat": "CPU Time IRate [{{instance}}]"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{instance=~\"$system\", area=\"heap\"} + ignoring(area) jvm_memory_bytes_used{instance=~\"$system\", area=\"nonheap\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{instance=~\"$system\"}[1m])",
     "legendFormat": "{{gc}} [{{instance}}]"
    }
   ]
  },
  {
   "title": "Process memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\"$system\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_state{state=\"WAITING\"}",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "jvm_threads_state{state=\"TIMED_WAITING\"}",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "jvm_threads_state{state=\"RUNNABLE\"}",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "jvm_threads_state{state=\"BLOCKED\"}",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "jvm_threads_state{state=\"NEW\"}",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "jvm_threads_state{state=\"TERMINATED\"}",
     "legendFormat": "{{state}}"
    }
   ]
  }
 ]
}