{
 "title": "Beacon Processor",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "options": {
    "content": "\n# Beacon Processor Metrics\n\nThe `BeaconProcessor` queues consensus messages from the network (gossip + rpc) and manages a set of worker tasks which consume those queues.\n\nThis is how consensus messages get from the network to the beacon chain."
   },
   "content": "\n# Attestation Processing Metrics\n\nMetrics regarding `BeaconChain::process_attestation`, which processes `Attestation` from the network (but not in blocks).\n\nCollected from the [`beacon_chain`](https://github.com/sigp/lighthouse/tree/master/beacon_node/beacon_chain) crate.\n\n\n\n"
  },
  {
   "title": "Unagg. Attestation Queue Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "beacon_processor_unaggregated_attestation_queue_total"
    }
   ]
  },
  {
   "title": "Agg. Attestation Queue Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "beacon_processor_aggregated_attestation_queue_total"
    }
   ]
  },
  {
   "title": "Gossip Block Queue Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "beacon_processor_gossip_block_queue_total"
    }
   ]
  },
  {
   "title": "RPC Block Queue Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "beacon_processor_rpc_block_queue_total"
    }
   ]
  },
  {
   "title": "Chain Segement Queue Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "beacon_processor_chain_segment_queue_total"
    }
   ]
  },
  {
   "title": "Exit Queue Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "beacon_processor_exit_queue_total"
    }
   ]
  },
  {
   "title": "Proposer Slashing Queue Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "beacon_processor_proposer_slashing_queue_total"
    }
   ]
  },
  {
   "title": "Attester Slashing Queue Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "beacon_processor_attester_slashing_queue_total"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 12 },
   "options": {
    "content": "\n### Work Events\n\n\nStats about the work events that are being received by the manager process.\n"
   },
   "content": "\n### Gossip Verification Times\n\n\nTimes to verify the attestation before re-gossiping\n"
  },
  {
   "title": "Worker Times",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_processor_worker_time_sum[1m])\n/\nrate(beacon_processor_worker_time_count[1m])"
    }
   ]
  },
  {
   "title": "Worker Times (Heatmap)",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "rate(beacon_processor_worker_time_sum[1m])\n/\nrate(beacon_processor_worker_time_count[1m])"
    }
   ]
  },
  {
   "title": "Work Events Received (1m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "none", "label": "Events" }
   ],
   "targets": [
    {
     "expr": "increase(beacon_processor_work_events_rx_count[1m])"
    }
   ]
  },
  {
   "title": "Work Events Started (1m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "increase(beacon_processor_work_events_started_count[1m])"
    }
   ]
  },
  {
   "title": "Work Events Ignored (1m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "increase(beacon_processor_work_events_ignored_count[1m])"
    }
   ]
  },
  {
   "title": "Work Event Handling Times for Manager",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_processor_event_handling_seconds_sum[5m])\n/\nrate(beacon_processor_event_handling_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "Work Event Handling Times for Manager (Heatmap)",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "rate(beacon_processor_event_handling_seconds_sum[5m])\n/\nrate(beacon_processor_event_handling_seconds_count[5m])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 31 },
   "options": {
    "content": "\n### Worker Stats\n\n\nStats about the workers that perform the heavy-lifting in gossip consensus message verification.\n"
   },
   "content": "\n### Gossip Verification Times\n\n\nTimes to verify the attestation before re-gossiping\n"
  },
  {
   "title": "Worker Idle Events per Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "none", "label": "Workers" }
   ],
   "targets": [
    {
     "expr": "increase(beacon_processor_idle_events_total[1m])"
    }
   ]
  },
  {
   "title": "Current Active Workers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "none", "label": "Workers" }
   ],
   "targets": [
    {
     "expr": "beacon_processor_workers_active_total"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 39 },
   "options": {
    "content": "\n### Beacon Blocks Received from Gossip"
   },
   "content": "\n### Gossip Verification Times\n\n\nTimes to verify the attestation before re-gossiping\n"
  },
  {
   "title": "Gossip Blocks Work Events Rx per Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "increase(beacon_processor_work_events_rx_count{type=\"gossip_block\"}[1m])"
    }
   ]
  },
  {
   "title": "RPC Blocks Work Events Started per Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "increase(beacon_processor_work_events_started_count{type=\"gossip_block\"}[1m])"
    }
   ]
  },
  {
   "title": "RPC Blocks Imported per Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 41 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "increase(beacon_processor_gossip_block_imported_total[1m])"
    }
   ]
  },
  {
   "title": "Gossip Block Gossip Worker Times",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_processor_worker_time_sum{type=\"gossip_block\"}[1m])\n/\nrate(beacon_processor_worker_time_count{type=\"gossip_block\"}[1m])"
    }
   ]
  },
  {
   "title": "Gossip Block Worker Times (Heatmap)",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "rate(beacon_processor_worker_time_sum{type=\"gossip_block\"}[1m])\n/\nrate(beacon_processor_worker_time_count{type=\"gossip_block\"}[1m])"
    }
   ]
  },
  {
   "title": "Gossip Blocks Imported per Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "increase(beacon_processor_gossip_block_imported_total[1m])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 59 },
   "options": {
    "content": "\n### Individual Beacon Blocks Received from RPC"
   },
   "content": "\n### Gossip Verification Times\n\n\nTimes to verify the attestation before re-gossiping\n"
  },
  {
   "title": "RPC Blocks Work Events Rx per Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "increase(beacon_processor_work_events_rx_count{type=\"rpc_block\"}[1m])"
    }
   ]
  },
  {
   "title": "RPC Blocks Work Events Started per Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 61 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "increase(beacon_processor_work_events_started_count{type=\"rpc_block\"}[1m])"
    }
   ]
  },
  {
   "title": "RPC Blocks Imported per Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 61 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "increase(beacon_processor_rpc_block_imported_total[1m])"
    }
   ]
  },
  {
   "title": "RPC Block Worker Times",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_processor_worker_time_sum{type=\"rpc_block\"}[1m])\n/\nrate(beacon_processor_worker_time_count{type=\"rpc_block\"}[1m])"
    }
   ]
  },
  {
   "title": "RPC Block Worker Times (Heatmap)",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "expr": "rate(beacon_processor_worker_time_sum{type=\"rpc_block\"}[1m])\n/\nrate(beacon_processor_worker_time_count{type=\"rpc_block\"}[1m])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 73 },
   "options": {
    "content": "\n### Chain Segments (Blocks) Received from RPC"
   },
   "content": "\n### Gossip Verification Times\n\n\nTimes to verify the attestation before re-gossiping\n"
  },
  {
   "title": "Chain Segement Work Events Received (1m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "increase(beacon_processor_work_events_rx_count{type=\"chain_segment\"}[1m])"
    }
   ]
  },
  {
   "title": "Chain Segment Work Events Started (1m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 75 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "increase(beacon_processor_work_events_rx_count{type=\"chain_segment\"}[1m])"
    }
   ]
  },
  {
   "title": "Chain Segment Work Events Ignored (1m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 75 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "increase(beacon_processor_work_events_ignored_count{type=\"chain_segment\"}[1m])"
    }
   ]
  },
  {
   "title": "Chain Segment Worker Times",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_processor_worker_time_sum{type=\"chain_segment\"}[1m])\n/\nrate(beacon_processor_worker_time_count{type=\"chain_segment\"}[1m])"
    }
   ]
  },
  {
   "title": "Chain Segment Worker Times (Heatmap)",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 81 },
   "targets": [
    {
     "expr": "rate(beacon_processor_worker_time_sum{type=\"chain_segment\"}[1m])\n/\nrate(beacon_processor_worker_time_count{type=\"chain_segment\"}[1m])"
    }
   ]
  },
  {
   "title": "Chain Segment Import Success per Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "increase(beacon_processor_chain_segment_success_total[1m])"
    }
   ]
  },
  {
   "title": "Chain Segment Import Failed per Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 87 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "increase(beacon_processor_chain_segment_failed_total[1m])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 93 },
   "options": {
    "content": "\n### Unaggregated Attestation Stats"
   },
   "content": "\n### Gossip Verification Times\n\n\nTimes to verify the attestation before re-gossiping\n"
  },
  {
   "title": "Unagg. Attestations Work Events Rx (1m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "increase(beacon_processor_work_events_rx_count{type=\"gossip_attestation\"}[1m])"
    }
   ]
  },
  {
   "title": "Unagg. Attestations Work Events Started (1m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 95 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "increase(beacon_processor_work_events_started_count{type=\"gossip_attestation\"}[1m])"
    }
   ]
  },
  {
   "title": "Unagg. Attestations Work Events Ignored (1m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 95 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "increase(beacon_processor_work_events_ignored_count{type=\"gossip_attestation\"}[1m])"
    }
   ]
  },
  {
   "title": "Unagg. Attestations Gossip-Verified per Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "increase(beacon_processor_unaggregated_attestation_verified_total[1m])"
    }
   ]
  },
  {
   "title": "Unagg. Attestations Imported per Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 101 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "increase(beacon_processor_unaggregated_attestation_imported_total[1m])"
    }
   ]
  },
  {
   "title": "Unaggregated Attn Gossip Worker Times",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 107 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_processor_worker_time_sum{type=\"gossip_attestation\"}[1m])\n/\nrate(beacon_processor_worker_time_count{type=\"gossip_attestation\"}[1m])"
    }
   ]
  },
  {
   "title": "Unaggregated Attn Gossip Worker Times (Heatmap)",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 107 },
   "targets": [
    {
     "expr": "rate(beacon_processor_worker_time_sum{type=\"gossip_attestation\"}[1m])\n/\nrate(beacon_processor_worker_time_count{type=\"gossip_attestation\"}[1m])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 113 },
   "options": {
    "content": "\n### Aggregated Attestation Stats"
   },
   "content": "\n### Gossip Verification Times\n\n\nTimes to verify the attestation before re-gossiping\n"
  },
  {
   "title": "Agg. Attestations Work Events Rx (1m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 115 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "increase(beacon_processor_work_events_rx_count{type=\"gossip_aggregate\"}[1m])"
    }
   ]
  },
  {
   "title": "Agg Attestations Work Events Started (1m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 115 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "increase(beacon_processor_work_events_started_count{type=\"gossip_aggregate\"}[1m])"
    }
   ]
  },
  {
   "title": "Agg Attestations Work Events Ignored (1m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 115 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "increase(beacon_processor_work_events_ignored_count{type=\"gossip_aggregate\"}[1m])"
    }
   ]
  },
  {
   "title": "Agg. Attestations Gossip-Verified per Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 121 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "increase(beacon_processor_aggregated_attestation_verified_total[1m])"
    }
   ]
  },
  {
   "title": "Agg. Attestations Imported per Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 121 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "increase(beacon_processor_aggregated_attestation_imported_total[1m])"
    }
   ]
  },
  {
   "title": "Aggregated Attn Gossip Worker Times",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 127 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_processor_worker_time_sum{type=\"gossip_aggregate\"}[1m])\n/\nrate(beacon_processor_worker_time_count{type=\"gossip_aggregate\"}[1m])"
    }
   ]
  },
  {
   "title": "Aggregated Attn Gossip Worker Times (Heatmap)",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 127 },
   "targets": [
    {
     "expr": "rate(beacon_processor_worker_time_sum{type=\"gossip_aggregate\"}[1m])\n/\nrate(beacon_processor_worker_time_count{type=\"gossip_aggregate\"}[1m])"
    }
   ]
  },
  {
   "title": "Agg. Attestations Started per Subnet",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 133 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "increase(beacon_processor_aggregated_attestation_subnet_id_total[5m])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 139 },
   "options": { "content": "\n### Voluntary Exit Stats" },
   "content": "\n### Gossip Verification Times\n\n\nTimes to verify the attestation before re-gossiping\n"
  },
  {
   "title": "Exit Work Events Rx (1m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 141 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "increase(beacon_processor_work_events_rx_count{type=\"gossip_voluntary_exit\"}[1m])"
    }
   ]
  },
  {
   "title": "Exit Work Events Started (1m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 141 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "increase(beacon_processor_work_events_started_count{type=\"gossip_voluntary_exit\"}[1m])"
    }
   ]
  },
  {
   "title": "Exit Work Events Ignored (1m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 141 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "increase(beacon_processor_work_events_ignored_count{type=\"gossip_voluntary_exit\"}[1m])"
    }
   ]
  },
  {
   "title": "Agg. Attestations Gossip-Verified per Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 147 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "increase(beacon_processor_exit_verified_total[1m])"
    }
   ]
  },
  {
   "title": "Exit Imported per Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 147 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "increase(beacon_processor_exit_imported_total[1m])"
    }
   ]
  },
  {
   "title": "Aggregated Attn Gossip Worker Times",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 153 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_processor_worker_time_sum{type=\"gossip_voluntary_exit\"}[1m])\n/\nrate(beacon_processor_worker_time_count{type=\"gossip_voluntary_exit\"}[1m])"
    }
   ]
  },
  {
   "title": "Aggregated Attn Gossip Worker Times (Heatmap)",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 153 },
   "targets": [
    {
     "expr": "rate(beacon_processor_worker_time_sum{type=\"gossip_voluntary_exit\"}[1m])\n/\nrate(beacon_processor_worker_time_count{type=\"gossip_voluntary_exit\"}[1m])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 159 },
   "options": { "content": "\n### Proposer Slashing Stats" },
   "content": "\n### Gossip Verification Times\n\n\nTimes to verify the attestation before re-gossiping\n"
  },
  {
   "title": "Proposer Slashing Work Events Rx (1m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 161 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "increase(beacon_processor_work_events_rx_count{type=\"gossip_proposer_slashing\"}[1m])"
    }
   ]
  },
  {
   "title": "Proposer Slashing Work Events Started (1m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 161 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "increase(beacon_processor_work_events_started_count{type=\"gossip_proposer_slashing\"}[1m])"
    }
   ]
  },
  {
   "title": "Proposer Slashing Work Events Ignored (1m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 161 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "increase(beacon_processor_work_events_ignored_count{type=\"gossip_proposer_slashing\"}[1m])"
    }
   ]
  },
  {
   "title": "Proposer Slashings Gossip-Verified per Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 167 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "increase(beacon_processor_proposer_slashing_verified_total[1m])"
    }
   ]
  },
  {
   "title": "Proposer Slashing Imported per Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 167 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "increase(beacon_processor_proposer_slashing_imported_total[1m])"
    }
   ]
  },
  {
   "title": "Proposer Slashing Gossip Worker Times",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 173 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_processor_worker_time_sum{type=\"gossip_proposer_slashing\"}[1m])\n/\nrate(beacon_processor_worker_time_count{type=\"gossip_proposer_slashing\"}[1m])"
    }
   ]
  },
  {
   "title": "Proposer Slashing Gossip Worker Times (Heatmap)",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 173 },
   "targets": [
    {
     "expr": "rate(beacon_processor_worker_time_sum{type=\"gossip_proposer_slashing\"}[1m])\n/\nrate(beacon_processor_worker_time_count{type=\"gossip_proposer_slashing\"}[1m])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 179 },
   "options": { "content": "\n### Attester Slashing Stats" },
   "content": "\n### Gossip Verification Times\n\n\nTimes to verify the attestation before re-gossiping\n"
  },
  {
   "title": "Attester Slashing Work Events Rx (1m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 181 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "increase(beacon_processor_work_events_rx_count{type=\"gossip_attester_slashing\"}[1m])"
    }
   ]
  },
  {
   "title": "Attester Slashing Work Events Started (1m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 181 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "increase(beacon_processor_work_events_started_count{type=\"gossip_attester_slashing\"}[1m])"
    }
   ]
  },
  {
   "title": "Attester Slashing Work Events Ignored (1m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 181 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "increase(beacon_processor_work_events_ignored_count{type=\"gossip_attester_slashing\"}[1m])"
    }
   ]
  },
  {
   "title": "Attester Slashings Gossip-Verified per Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 187 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "increase(beacon_processor_attester_slashing_verified_total[1m])"
    }
   ]
  },
  {
   "title": "Attester Slashing Imported per Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 187 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "increase(beacon_processor_attester_slashing_imported_total[1m])"
    }
   ]
  },
  {
   "title": "Attester Slashing Gossip Worker Times",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 193 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_processor_worker_time_sum{type=\"gossip_attester_slashing\"}[1m])\n/\nrate(beacon_processor_worker_time_count{type=\"gossip_attester_slashing\"}[1m])"
    }
   ]
  },
  {
   "title": "Attester Slashing Gossip Worker Times (Heatmap)",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 193 },
   "targets": [
    {
     "expr": "rate(beacon_processor_worker_time_sum{type=\"gossip_attester_slashing\"}[1m])\n/\nrate(beacon_processor_worker_time_count{type=\"gossip_attester_slashing\"}[1m])"
    }
   ]
  }
 ]
}