{
 "title": "Block Processing",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "content": "\n# Block Processing Metrics\n\nMetrics collected from a Lighthouse Beacon Node about a `BeaconChain` processing `BeaconBlocks`.\n\nCollected from the `beacon_chain` crate.\n\n\n\n"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "content": "\n### Committees/Shuffling\n\n\nCheck that the committees cache is build, building if not.\n"
  },
  {
   "title": "Block Processing Total Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 2 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_block_processing_seconds_sum[30s])\n/\nrate(beacon_block_processing_seconds_count[30s])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 9, "x": 0, "y": 8 },
   "content": "\n### Read from database\n\n\nCheck that the hash isn't already known in the database, load the block and state for processing.\n"
  },
  {
   "title": "Get Parent Block & State",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_block_processing_db_read_seconds_sum[1m])\n/\nrate(beacon_block_processing_db_read_seconds_count[1m])"
    }
   ]
  },
  {
   "title": "Write Imported Block & State to DB",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_block_processing_db_write_seconds_sum[30s])\n/\nrate(beacon_block_processing_db_write_seconds_count[30s])"
    }
   ]
  },
  {
   "title": "Block Processing Committee Times",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_block_processing_committee_building_seconds_sum[5m])\n/\nrate(beacon_block_processing_committee_building_seconds_count[5m])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 14, "x": 0, "y": 16 },
   "content": "\n### Run per_block_processing\n\n\nThe core `state_processing::per_block_processing` verification/state updating function, as defined in the spec.\n"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 16 },
   "content": "\n### Tree hash the beacon state\n\n\nGet the merkle root of the state after `state_processing::per_block_processing`\n"
  },
  {
   "title": "Block Processing Core-Processing Times",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_block_processing_core_seconds_sum[1m])\n/\nrate(beacon_block_processing_core_seconds_count[1m])"
    }
   ]
  },
  {
   "title": "Block Processing State Hashing Times",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_block_processing_state_root_seconds_sum[1m])\n/\nrate(beacon_block_processing_state_root_seconds_count[1m])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 24 },
   "content": "\n### Update the fork choice algorithm\n\n\nSubmit the block (and all containied attestation) to the LMD GHOST fork choice algorithm. Does not find the head, just updates the votes.\n"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 24 },
   "content": "\n### Checkpoint Cache\n\n\nNot specific to block production, but shows how many times we hit/miss the cache of recently used blocks/states.\n"
  },
  {
   "title": "Block Processing Fork Choice Register Times",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_block_processing_fork_choice_register_seconds_sum[1m])\n/\nrate(beacon_block_processing_fork_choice_register_seconds_count[1m])"
    }
   ]
  },
  {
   "title": "Checkpoint Cache Hits",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "beacon_checkpoint_cache_hits_total"
    }
   ]
  },
  {
   "title": "Checkpoint Cache Misses",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "beacon_checkpoint_cache_misses_total"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 33 },
   "content": "\n### Per slot processing\n\n\nUsing the `per_slot_processing` function to bring the state of the parent block into the slot of the block being produced.\n"
  },
  {
   "title": "Catch Up State Time",
   "type": "graph",
   "description": "Time it takes to bring the parent block state up to the slot of the block being produced",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_block_processing_catch_up_state_seconds_sum[1m])\n/\nrate(beacon_block_processing_catch_up_state_seconds_count[1m])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 41 },
   "content": "\n### Outlier Analysis\n\nMetrics that show outliers in block processing more effectively than the averaging graphs\n"
  },
  {
   "title": "Block Processing Time Heatmap",
   "type": "heatmap",
   "description": "Frequency of different block processing times, shows outliers more effectively than the averaging view",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "increase(beacon_block_processing_seconds_sum[10s])"
    }
   ]
  },
  {
   "title": "DB Write Times Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "increase(beacon_block_processing_db_write_seconds_sum[10s])"
    }
   ]
  }
 ]
}