{
 "title": "Database",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "content": "\n# Database Metrics\n\nMetrics collected from a Lighthouse Beacon Node regarding the core key-value database (e.g., LevelDB).\n\nCollected from the [`store`](https://github.com/sigp/lighthouse/tree/master/beacon_node/store) crate.\n\n\n\n"
  },
  {
   "title": "On-Disk Database Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "store_disk_db_size" }
   ]
  },
  {
   "title": "Freezer Database Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "store_freezer_db_size" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 12 },
   "content": "\n### Global database read/write times\n\n\nThe times it takes to read and write plain bytes to the database.\n"
  },
  {
   "title": "Database Read Times",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(store_disk_db_read_seconds_sum[5m])\n/\nrate(store_disk_db_read_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "Database Write Times",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(store_disk_db_write_seconds_sum[5m])\n/\nrate(store_disk_db_write_seconds_count[5m])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 19 },
   "content": "\n### Reads per Minute\n\n\nThe global database reads per minute, expressed as operations and a cumulative bytes value.\n"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 19 },
   "content": "\n### Writes per Minute\n\n\nThe global database writes per minute, expressed as operations and a cumulative bytes value.\n"
  },
  {
   "title": "DB Read Operations per Minute",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "Ops per Minute" }
   ],
   "targets": [
    {
     "expr": "increase(store_disk_db_read_count_total [1m])"
    }
   ]
  },
  {
   "title": "DB Read Write (1m avg)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "Ops per Minute" }
   ],
   "targets": [
    {
     "expr": "increase(store_disk_db_write_count_total [1m])"
    }
   ]
  },
  {
   "title": "DB Throughput (Read) per Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "decbytes", "label": "Bytes per Minute" }
   ],
   "targets": [
    {
     "expr": "increase(store_disk_db_read_bytes_total [1m])"
    }
   ]
  },
  {
   "title": "DB Throughput (Write) (1m avg)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "decbytes", "label": "Bytes per Minute" }
   ],
   "targets": [
    {
     "expr": "increase(store_disk_db_write_bytes_total [1m])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 32 },
   "content": "\n### LRU Caches\n\n\nEffectiveness of the LRU caches for blocks and states.\n"
  },
  {
   "title": "State Cache Hit Rate",
   "type": "graph",
   "description": "Percentage of hot states loaded from the cache (no disk read)",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "increase(store_beacon_state_cache_hit_total[1m])\n/\nincrease(store_beacon_state_hot_get_total[1m])"
    }
   ]
  },
  {
   "title": "Block Cache Hit Rate",
   "type": "graph",
   "description": "Percentage of blocks loaded which came from the cache (and avoided a disk read entirely)",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "increase(store_beacon_block_cache_hit_total[1m])\n/\nincrease(store_beacon_state_get_total[1m])"
    }
   ]
  },
  {
   "title": "Cached State Clone Time",
   "type": "graph",
   "description": "Time required to clone a BeaconState from the cache",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(store_beacon_state_cache_clone_time_sum[1m])\n/\nrate(store_beacon_state_cache_clone_time_count[1m])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 44 },
   "content": "\n### Beacon state read/write overhead\n\n\nThe encoding/decoding overheads of storing `BeaconState` (excluding action bytes read/write operations).\n"
  },
  {
   "title": "Beacon State Read Overhead",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(store_beacon_state_read_overhead_seconds_sum[5m])\n/\nrate(store_beacon_state_read_overhead_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "Beacon State Write Overhead",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(store_beacon_state_write_overhead_seconds_sum[5m])\n/\nrate(store_beacon_state_write_overhead_seconds_count[5m])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 51 },
   "content": "\n### BeaconState read/writes\n\n\nNumber of `BeaconState` read/writes in operations and cumulative bytes.\n"
  },
  {
   "title": "Beacon State Reads (Bytes/Minute)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "increase(store_beacon_state_read_bytes_total[1m])"
    }
   ]
  },
  {
   "title": "Beacon State Writes (Bytes/Minute)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 51 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "increase(store_beacon_state_write_bytes_total[1m])"
    }
   ]
  },
  {
   "title": "Beacon State Reads (Ops/Minute)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "expr": "increase(store_beacon_state_read_total[1m])"
    }
   ]
  },
  {
   "title": "Beacon State Writes (Ops/Minute)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 56 },
   "yaxes": [
    { "format": "wpm", "label": "Number of Ops" }
   ],
   "targets": [
    {
     "expr": "increase(store_beacon_state_write_total[1m])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 61 },
   "content": "\n### Beacon block read/write overhead\n\n\nThe encoding/decoding overheads of storing `BeaconBlock` (excluding action bytes read/write operations).\n"
  },
  {
   "title": "Beacon Block Read Overhead",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(store_beacon_block_read_overhead_seconds_sum[5m])\n/\nrate(store_beacon_block_read_overhead_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "Beacon Block Write Overhead",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(store_beacon_block_write_overhead_seconds_sum[5m])\n/\nrate(store_beacon_block_write_overhead_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "Beacon Block Reads (Bytes per Minute)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "increase(store_beacon_block_read_bytes_total [1m])"
    }
   ]
  },
  {
   "title": "Beacon Block Writes (Bytes)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 68 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "store_beacon_block_write_bytes_total"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 68 },
   "content": "\n### BeaconBlock read/writes\n\n\nNumber of `BeaconBlock` read/writes in operations and cumulative bytes.\n"
  },
  {
   "title": "Beacon Block Reads (Ops per Minute)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "none", "label": "Number of Ops" }
   ],
   "targets": [
    {
     "expr": "increase(store_beacon_block_read_total[1m])"
    }
   ]
  },
  {
   "title": "Beacon Block Writes (Ops)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 73 },
   "yaxes": [
    { "format": "sci", "label": "Number of Ops" }
   ],
   "targets": [
    {
     "expr": "store_beacon_block_write_bytes_total"
    }
   ]
  }
 ]
}