{
 "title": "Network Propagation",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 0 },
   "content": "\n# Network Propagation\n\nOverview of message propagation on the network.\n\n\n\n"
  },
  {
   "title": "Avg. Active Validators",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(beacon_head_state_active_validators_total)"
    }
   ]
  },
  {
   "title": "Avg. Current Slot",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    { "expr": "max(slotclock_present_slot)" }
   ]
  },
  {
   "title": "Avg. Current Epoch",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    { "expr": "max(slotclock_present_epoch)" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 3 },
   "content": "\n### Chain Health\n\nOverview of the health of the chain.\n\n\n"
  },
  {
   "title": "Slots since Best Block",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Slots" }
   ],
   "targets": [
    {
     "expr": "slotclock_present_slot - beacon_head_state_slot"
    }
   ]
  },
  {
   "title": "Epoch Boundaries since Justification (Min)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Epochs" }
   ],
   "targets": [
    {
     "expr": "slotclock_present_epoch - beacon_head_state_current_justified_epoch"
    }
   ]
  },
  {
   "title": "Epoch Boundaries since Finalization (Min)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Epochs" }
   ],
   "targets": [
    {
     "expr": "slotclock_present_epoch - beacon_head_state_finalized_epoch"
    }
   ]
  },
  {
   "title": "Previous Epoch Attesting Balance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percentunit", "label": "Percentage of Balance" }
   ],
   "targets": [
    {
     "expr": "beacon_participation_prev_epoch_attester"
    }
   ]
  },
  {
   "title": "Previous Epoch Target Attesting Balance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "percentunit", "label": "Percentage of Balance" }
   ],
   "targets": [
    {
     "expr": "beacon_participation_prev_epoch_target_attester"
    }
   ]
  },
  {
   "title": "Previous Epoch Head Attesting Balance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "percentunit", "label": "Percentage of Balance" }
   ],
   "targets": [
    {
     "expr": "beacon_participation_prev_epoch_head_attester"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 16 },
   "content": "\n### Beacon Chain Caches\n\nStats from caches on the `BeaconChain`. Useful for determining what is reaching the `BeaconChain`.\n\n\n\n"
  },
  {
   "title": "Previous Epoch Observed Attesters",
   "type": "graph",
   "description": "The number of attesters for which we have seen an attestation. That attestation is not necessarily included in the chain.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none", "label": "# of Validators" }
   ],
   "targets": [
    {
     "expr": "beacon_attn_observation_epoch_attesters"
    }
   ]
  },
  {
   "title": "Previous Epoch Observed Aggregators",
   "type": "graph",
   "description": "The number of aggregators for which we have seen an attestation. That attestation is not necessarily included in the chain.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "none", "label": "# of Validators" }
   ],
   "targets": [
    {
     "expr": "beacon_attn_observation_epoch_aggregators"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 23 },
   "content": "\n### Gossip Rx\n\nTypes of messages _recieved_ from the gossip network.\n\n\n\n"
  },
  {
   "title": "Gossip Blocks Received per 5 Minutes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "none", "label": "Blocks" }
   ],
   "targets": [
    {
     "expr": "increase(network_gossip_blocks_rx_total[5m])"
    }
   ]
  },
  {
   "title": "Gossip Aggregated Attestations Received per Minute",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "increase(network_gossip_aggregated_attestations_rx_total[1m])"
    }
   ]
  },
  {
   "title": "Gossip Unaggregated Attestations Received per Minute",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "increase(network_gossip_unaggregated_attestations_rx_total[1m])"
    }
   ]
  },
  {
   "title": "Gossip Unaggregated Attestations Ignored per Minute",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "increase(network_gossip_unaggregated_attestations_ignored_total[1m])"
    }
   ]
  },
  {
   "title": "Percentage of Unagg. Attns Processed per Minute",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "percentunit", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "1 - (increase(network_gossip_unaggregated_attestations_ignored_total[1m]) / increase(network_gossip_unaggregated_attestations_rx_total[1m]))"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 35 },
   "content": "### Attestation Subnet Subscriptions\n\nSubscriptions to unaggregated attestation subnets."
  },
  {
   "title": "Total Subnet Subscription Requests per Minute",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "none", "label": "# of Validators" }
   ],
   "targets": [
    {
     "expr": "increase(network_subnet_subscriptions_total[1m])"
    }
   ]
  },
  {
   "title": "Total Subnet Subscription Requests for Aggregators per Minute",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "none", "label": "# of Validators" }
   ],
   "targets": [
    {
     "expr": "increase(network_subnet_subscriptions_aggregator_total[1m])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 35 },
   "content": "\n### Gossip Tx\n\nTypes of messages _transmitted_ from the gossip network. I'm pretty sure this doesn't include re-transmitted gossip messages. \n\n\n\n"
  },
  {
   "title": "Gossip Blocks Transmitted per 5 Minutes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "none", "label": "Blocks" }
   ],
   "targets": [
    {
     "expr": "increase(network_gossip_blocks_tx_total[5m])"
    }
   ]
  },
  {
   "title": "Gossip Unaggregated Attestations Transmitted per Minute",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 37 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "increase(network_gossip_unaggregated_attestations_tx_total[1m])"
    }
   ]
  },
  {
   "title": "Gossip Aggregated Attestations Transmitted per Minute",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 37 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "increase(network_gossip_aggregated_attestations_tx_total[1m])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 42 },
   "content": "\n### Logging\n\nRates of different types of logs\n\n"
  },
  {
   "title": "Crit Logs Total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "crit_total" }
   ]
  },
  {
   "title": "Error Logs per Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 44 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "rate(error_total[1m])" }
   ]
  },
  {
   "title": "Warn Logs per Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "rate(warn_total[1m])" }
   ]
  },
  {
   "title": "Info Logs per Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 44 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "rate(info_total[1m])" }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 12, "x": 0, "y": 50 }, "content": "\n### Peers\n\n\n\n" },
  { "type": "text", "gridPos": { "h": 2, "w": 12, "x": 12, "y": 50 }, "content": "\n### Syncing\n\n\n\n" },
  {
   "title": "libp2p Connected Peers",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short", "label": "Peers" }
   ],
   "targets": [
    {
     "expr": "libp2p_peer_connected_peers_total"
    }
   ]
  },
  {
   "title": "Syncing Slots per Second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "none", "label": "Slots" }
   ],
   "targets": [
    { "expr": "sync_slots_per_second" }
   ]
  }
 ]
}