{
 "title": "Summary",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "content": "\n# Lighthouse Metrics\n\nMetrics collected from a Lighthouse Beacon Node.\n\n\n\n"
  },
  {
   "title": "Avg. Validator Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(beacon_head_state_total_validators_total)"
    }
   ]
  },
  {
   "title": "Avg. Withdrawable Validators",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(beacon_head_state_withdrawn_validators_total)"
    }
   ]
  },
  {
   "title": "Slots per Epoch",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "avg(slotclock_slots_per_epoch)" }
   ]
  },
  {
   "title": "Avg. Current Slot",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    { "expr": "max(slotclock_present_slot)" }
   ]
  },
  {
   "title": "Avg. Slashed Validators",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(beacon_head_state_slashed_validators_total)"
    }
   ]
  },
  {
   "title": "Avg. Active Validators",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(beacon_head_state_active_validators_total)"
    }
   ]
  },
  {
   "title": "Seconds per Slot",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 3 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(slotclock_slot_time_milliseconds)"
    }
   ]
  },
  {
   "title": "Avg. Current Epoch",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    { "expr": "max(slotclock_present_epoch)" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 6 },
   "content": "\n### Consensus\n\nOverview of consensus between nodes.\n\n\n"
  },
  {
   "title": "Slots since Best Block",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Slots" }
   ],
   "targets": [
    {
     "expr": "slotclock_present_slot - beacon_head_state_slot"
    }
   ]
  },
  {
   "title": "Epoch Boundaries since Justification (Min)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Epochs" }
   ],
   "targets": [
    {
     "expr": "slotclock_present_epoch - beacon_head_state_current_justified_epoch"
    }
   ]
  },
  {
   "title": "Epoch Boundaries since Finalization (Min)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Epochs" }
   ],
   "targets": [
    {
     "expr": "slotclock_present_epoch - beacon_head_state_finalized_epoch"
    }
   ]
  },
  {
   "title": "Previous Epoch Attesting Balance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percentunit", "label": "Percentage of Balance" }
   ],
   "targets": [
    {
     "expr": "beacon_participation_prev_epoch_attester"
    }
   ]
  },
  {
   "title": "Previous Epoch Target Attesting Balance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 13, "y": 14 },
   "yaxes": [
    { "format": "percentunit", "label": "Percentage of Balance" }
   ],
   "targets": [
    {
     "expr": "beacon_participation_prev_epoch_target_attester"
    }
   ]
  },
  {
   "title": "Previous Epoch Head Attesting Balance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 14 },
   "yaxes": [
    { "format": "percentunit", "label": "Percentage of Balance" }
   ],
   "targets": [
    {
     "expr": "beacon_participation_prev_epoch_head_attester"
    }
   ]
  },
  {
   "title": "Previous Epoch Observed Attesters",
   "type": "graph",
   "description": "The number of attesters for which we have seen an attestation. That attestation is not necessarily included in the chain.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "none", "label": "# of Validators" }
   ],
   "targets": [
    {
     "expr": "beacon_attn_observation_epoch_attesters"
    }
   ]
  },
  {
   "title": "Previous Epoch Observed Aggregators",
   "type": "graph",
   "description": "The number of aggregators for which we have seen an attestation. That attestation is not necessarily included in the chain.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "none", "label": "# of Validators" }
   ],
   "targets": [
    {
     "expr": "beacon_attn_observation_epoch_aggregators"
    }
   ]
  },
  {
   "title": "Validator Balances",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "none", "label": "Total Validator ETH" }
   ],
   "targets": [
    {
     "expr": "beacon_head_state_validator_balances_total / 1000000000"
    }
   ]
  },
  {
   "title": "Active Validators",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 24 },
   "yaxes": [
    { "format": "none", "label": "Total Validator ETH" }
   ],
   "targets": [
    {
     "expr": "beacon_head_state_active_validators_total"
    }
   ]
  },
  {
   "title": "Total Validators",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 24 },
   "yaxes": [
    { "format": "none", "label": "Total Validator ETH" }
   ],
   "targets": [
    {
     "expr": "beacon_head_state_total_validators_total"
    }
   ]
  },
  {
   "title": "Finalized Root (hash shown as int)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 24 },
   "yaxes": [
    { "format": "sci", "label": "int(hash)" }
   ],
   "targets": [
    {
     "expr": "beacon_head_state_finalized_root"
    }
   ]
  },
  {
   "title": "Total Fork Choice Re-Orgs",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 24 },
   "yaxes": [
    { "format": "none", "label": "Re-Orgs" }
   ],
   "targets": [
    { "expr": "beacon_fork_choice_reorg_total" }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 28 }, "content": "\n### Networking\n\n\n\n" },
  {
   "title": "libp2p Connected Peers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "Peers" }
   ],
   "targets": [
    {
     "expr": "libp2p_peer_connected_peers_total"
    }
   ]
  },
  {
   "title": "Unsolicited Discovery Requests/s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "discovery_requests", "legendFormat": "Discovery Requests Per Second" }
   ]
  },
  {
   "title": "Active Discv5 Sessions",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "discovery_sessions", "legendFormat": "Sessions" }
   ]
  },
  {
   "title": "Queued Discovery Queries",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "discovery_queue_size", "legendFormat": "Queued Discoveries" }
   ]
  },
  {
   "title": "Unsolicited Requests/s",
   "type": "bargauge",
   "description": "The peers requesting routing information from us. Requests per second",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "discovery_reqs_per_ip", "legendFormat": "{{Addresses}}" }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 41 }, "content": "\n### Logging\n\n\n\n" },
  {
   "title": "Crit Logs Total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "crit_total" }
   ]
  },
  {
   "title": "Error Logs per Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 43 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "rate(error_total[1m])" }
   ]
  },
  {
   "title": "Warn Logs per Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "rate(warn_total[1m])" }
   ]
  },
  {
   "title": "Info Logs per Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 43 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "rate(info_total[1m])" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 49 },
   "content": "\n### Core BeaconChain Functions\n\nTiming of core `BeaconChain` functions and syncing.\n\n\n"
  },
  {
   "title": "Block Processing Times (24s moving avg)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_block_processing_seconds_sum[24s])/rate(beacon_block_processing_seconds_count[24s])"
    }
   ]
  },
  {
   "title": "Attestation Processing Times (5m Avg)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 51 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_attestation_processing_seconds_sum[5m])\n/\nrate(beacon_attestation_processing_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "Find & Update Head Routine (1m avg)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_fork_choice_seconds_sum[1m])\n/\nrate(beacon_fork_choice_seconds_count[1m])"
    }
   ]
  },
  {
   "title": "Syncing Slots per Second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 51 },
   "yaxes": [
    { "format": "none", "label": "Slots" }
   ],
   "targets": [
    { "expr": "sync_slots_per_second" }
   ]
  },
  {
   "title": "Block Production Times (5m avg)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_block_production_seconds_sum[5m])\n/\nrate(beacon_block_production_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "Attestation Production Times",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 56 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_attestation_production_seconds_sum[1m])\n/\nrate(beacon_attestation_production_seconds_count[1m])"
    }
   ]
  },
  {
   "title": "State Tree Hash Times (5m avg)",
   "type": "graph",
   "description": "Time taken to calculate the tree hash root of a BeaconState during block processing.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_block_processing_state_root_seconds_sum[5m])\n/\nrate(beacon_block_processing_state_root_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "Block Tree Hash Times (5m avg)",
   "type": "graph",
   "description": "Time taken to calculate the tree hash root of a BeaconState during block processing.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 56 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_block_processing_block_root_seconds_sum[5m])\n/\nrate(beacon_block_processing_block_root_seconds_count[5m])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 61 },
   "content": "\n### Task Manager\nActive long standing threads\n\n\n\n"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 61 },
   "content": "\n### HTTP Server\n\nUsed by Prometheus and the RESTful API.\n\n\n\n"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 61 },
   "content": "\n### Database\n\nStats about the on-disk database (LevelDB)\n\n\n\n"
  },
  {
   "title": "Async tasks count",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 63 },
   "targets": [
    { "expr": "async_tasks_count", "legendFormat": "{{async_task_count}}" }
   ]
  },
  {
   "title": "HTTP Server Request Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 63 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_request_duration_seconds_sum[5m])\n/\nrate(http_server_request_duration_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "On-Disk Database Size (Hot DB Only)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "store_disk_db_size" }
   ]
  },
  {
   "title": "DB Throughput (Read) per Minute",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "decbytes", "label": "Bytes per Minute" }
   ],
   "targets": [
    {
     "expr": "increase(store_disk_db_read_bytes_total [1m])"
    }
   ]
  },
  {
   "title": "DB Throughput (Write) (1m avg)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 68 },
   "yaxes": [
    { "format": "decbytes", "label": "Bytes per Minute" }
   ],
   "targets": [
    {
     "expr": "increase(store_disk_db_write_bytes_total [1m])"
    }
   ]
  },
  {
   "title": "Persist Beacon Chain Times (1m avg)",
   "type": "graph",
   "description": "Time taken to calculate the tree hash root of a BeaconState during block processing.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_persist_chain_sum[1m])\n/\nrate(beacon_persist_chain_count[1m])"
    }
   ]
  }
 ]
}