{
 "title": "Prysm gRPC stats",
 "tags": [ "Prysm" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "version",
    "query": "go_info{component=\"beacon-chain\"}"
   },
   {
    "name": "grpc_method",
    "query": "grpc_server_handling_seconds_bucket{component=\"beacon-chain\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "gRPC Requests per Second",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{component=\"beacon-chain\", version=~\"${version:pipe}\", grpc_method=~\"${grpc_method:pipe}\"}[5m])) by (version, grpc_method)\n",
     "legendFormat": "{{version}}-{{grpc_method}}"
    }
   ]
  },
  {
   "title": "gRPC Failure Rate",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{component=\"beacon-chain\",version=~\"${version:pipe}\", grpc_method=~\"${grpc_method:pipe}\", grpc_code!=\"OK\"}[5m])) by (version, grpc_method) / sum(rate(grpc_server_handled_total{component=\"beacon-chain\",version=~\"${version:pipe}\", grpc_method=~\"${grpc_method:pipe}\"}[5m])) by (version, grpc_method)",
     "legendFormat": "{{version}}-{{grpc_method}}"
    }
   ]
  },
  { "title": "$grpc_method", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }, "repeat": "grpc_method" },
  {
   "title": "gRPC Latency ($version )",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 16 },
   "repeat": "version",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  sum(rate(grpc_server_handling_seconds_bucket{component=\"beacon-chain\",grpc_type=\"unary\",grpc_method=\"$grpc_method\",version=~\"${version:pipe}\"}[5m])) by (le)\n) * 1000",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.90, \n  sum(rate(grpc_server_handling_seconds_bucket{component=\"beacon-chain\",grpc_type=\"unary\",grpc_method=\"$grpc_method\",version=~\"${version:pipe}\"}[5m])) by (le)\n) * 1000",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.50, \n  sum(rate(grpc_server_handling_seconds_bucket{component=\"beacon-chain\",grpc_type=\"unary\",grpc_method=\"$grpc_method\",version=~\"${version:pipe}\"}[5m])) by (le)\n) * 1000",
     "legendFormat": "P50"
    }
   ]
  }
 ]
}