{
 "title": "Ethereum 2.0",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Network Beacon Chain",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Local Beacon Chain",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Network Validators",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 9, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Slots/Epochs",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Participation Rate",
   "type": "stat",
   "description": "The percentage of ETH balances expected to attest that are actually attesting.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(total_voted_target_balances{} / total_eligible_balances{} )"
    }
   ]
  },
  {
   "title": "Network Liveness",
   "type": "stat",
   "description": "A metric expressing the distance between the current finalized epoch and the expected finalized epoch based on the genesis time. 100% means the expected and current finalized epochs are the same. The metric reaches 0% when the finalized epoch is 25 epochs behind the expected epoch.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min((1-(4*((floor(beacon_clock_time_slot{}/32) - beacon_finalized_epoch{} - 2)/100))),0)"
    }
   ]
  },
  {
   "title": "Beacon Uptime",
   "type": "singlestat",
   "description": "The length of time the beacon chain process has been running",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "format": "h",
   "valueName": "current",
   "targets": [
    {
     "expr": "(time()-process_start_time_seconds{job=\"beacon\"})/3600"
    }
   ]
  },
  {
   "title": "Beacon Log Messages",
   "type": "stat",
   "description": "Average number of log messages received per hour over the selected time range",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "/hr" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(log_entries_total{level=\"error\",job=\"beacon\"}[$__range]))*3600",
     "legendFormat": "errors"
    },
    {
     "expr": "sum(rate(log_entries_total{level=\"warning\",job=\"beacon\"}[$__range]))*3600",
     "legendFormat": "warnings"
    }
   ]
  },
  {
   "title": "Validator Counts",
   "type": "stat",
   "description": "Counts of active, slashed and exited validators.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "validator_count{state=\"Active\"} ",
     "legendFormat": "active"
    },
    {
     "expr": "validator_count{state=\"Slashed\"} ",
     "legendFormat": "slashed"
    },
    {
     "expr": "validator_count{state=\"Exited\"} ",
     "legendFormat": "exited"
    }
   ]
  },
  {
   "title": "Validator Queues",
   "type": "stat",
   "description": "Current number of pending and exiting validators",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "validator_count{state=\"Pending\"}",
     "legendFormat": "pending"
    },
    {
     "expr": "validator_count{state=\"Exiting\"}",
     "legendFormat": "exiting"
    }
   ]
  },
  {
   "title": "Queue Lengths",
   "type": "stat",
   "description": "Estimated length of time until all pending and exiting validators have cleared the queues.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((validator_count{state=\"Pending\"}/4)*6.4)",
     "legendFormat": "pending"
    },
    {
     "expr": "((validator_count{state=\"Exiting\"}/4)*6.4)",
     "legendFormat": "exiting"
    }
   ]
  },
  {
   "title": "Epochs",
   "type": "stat",
   "description": "Current, justified, and finalized epochs. In this order, these three values should be sequentially decreasing.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(beacon_clock_time_slot{} / 32)",
     "legendFormat": "current"
    },
    {
     "expr": "beacon_current_justified_epoch{}",
     "legendFormat": "justified"
    },
    { "expr": "beacon_finalized_epoch {} ", "legendFormat": "finalized" }
   ]
  },
  {
   "title": "Participation Rate",
   "type": "graph",
   "description": "The percentage of ETH balances expected to attest that are actually attesting.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percentunit", "label": "Participation Rate" }
   ],
   "targets": [
    {
     "expr": "(total_voted_target_balances{} / total_eligible_balances{} )",
     "legendFormat": "participation rate"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "graph",
   "description": "The number of peers to which the beacon chain is connected",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "Peers" }
   ],
   "targets": [
    {
     "expr": "p2p_peer_count{state=\"Connected\"}",
     "legendFormat": "peers"
    }
   ]
  },
  {
   "title": "Avg. Balance",
   "type": "singlestat",
   "description": "Average validator balance across the network",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "validators_total_balance{state=\"Active\"} / validator_count{state=\"Active\"} / 1000000000",
     "legendFormat": "eth"
    }
   ]
  },
  {
   "title": "Validators",
   "type": "graph",
   "description": "Number of pending and existing validators over time. Pending validators are shown as positive values, while exiting validators are shown as negative values.",
   "gridPos": { "h": 6, "w": 6, "x": 15, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "validators" }
   ],
   "targets": [
    {
     "expr": "validator_count{state=\"Pending\"}",
     "legendFormat": "pending"
    },
    {
     "expr": "validator_count{state=\"Exiting\"}",
     "legendFormat": "exiting"
    },
    {
     "expr": "validator_count{state=\"Slashing\"}",
     "legendFormat": "slashing"
    },
    {
     "expr": "validator_count{state=\"Active\"}",
     "legendFormat": "active validators"
    }
   ]
  },
  {
   "title": "Slots",
   "type": "stat",
   "description": "Current slot and head slot",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "beacon_slot{}", "legendFormat": "current slot" },
    { "expr": "beacon_head_slot{}", "legendFormat": "head slot" }
   ]
  },
  {
   "title": "Stake Effectiveness",
   "type": "singlestat",
   "description": "The percentage of all validator balances earning returns. Equal to effective balance of all validators divided by the total balance of all validators.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 7 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "validators_total_effective_balance{state=\"Active\"}/validators_total_balance{state=\"Active\"}"
    }
   ]
  },
  {
   "title": "Slots Behind",
   "type": "singlestat",
   "description": "The difference between the expected slot based on the genesis time and the current head slot. Ideally this is zero.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "beacon_clock_time_slot-beacon_head_slot{}",
     "legendFormat": "slots"
    }
   ]
  },
  {
   "title": "Server",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Local Validators",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Memory usage on the server",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "decbytes", "label": "GB" }
   ],
   "targets": [
    {
     "expr": "( node_memory_MemTotal_bytes{} - node_memory_MemFree_bytes{} - node_memory_Buffers_bytes{} - node_memory_Cached_bytes{} - node_memory_SwapCached_bytes{} - node_memory_Slab_bytes{} - node_memory_PageTables_bytes{} - node_memory_VmallocUsed_bytes{} ) or ( node_memory_MemTotal{} - node_memory_MemFree{} - node_memory_Buffers{} - node_memory_Cached{} - node_memory_SwapCached{} - node_memory_Slab{} - node_memory_PageTables{} - node_memory_VmallocUsed{} )",
     "legendFormat": "apps"
    },
    {
     "expr": "node_memory_Buffers_bytes{} or node_memory_Buffers{}",
     "legendFormat": "buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{} or node_memory_Cached{}",
     "legendFormat": "cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{} or node_memory_MemFree{}",
     "legendFormat": "free"
    },
    {
     "expr": "node_memory_Slab_bytes{} or node_memory_Slab{}",
     "legendFormat": "slab"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "description": "Network transmission (tx) and reception (rx) rates",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{device='eno1'}[5m])*8 or irate(node_network_transmit_bytes{device='eno1'}[5m])*8",
     "legendFormat": "tx"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device='eno1'}[5m])*8 or irate(node_network_receive_bytes{device='eno1'}[5m])*8",
     "legendFormat": "rx"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "The length of time the validator process has been running",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 11 },
   "format": "h",
   "valueName": "current",
   "targets": [
    {
     "expr": "(time()-process_start_time_seconds{job=\"validator\"})/3600"
    }
   ]
  },
  {
   "title": "Validator Log Messages",
   "type": "stat",
   "description": "Average number of log messages received per hour over the selected time range",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "/hr" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(log_entries_total{level=\"error\",job=\"validator\"}[$__range]))*3600",
     "legendFormat": "errors"
    },
    {
     "expr": "sum(rate(log_entries_total{level=\"warning\",job=\"validator\"}[$__range]))*3600",
     "legendFormat": "warnings"
    }
   ]
  },
  {
   "title": "Total Earnings  (ETH)",
   "type": "singlestat",
   "description": "Total ETH return on the initial effective stake of active local validators.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(validator_balance{})-(count(validator_balance{} > 16 and validator_statuses{} == 3)*32)"
    }
   ]
  },
  {
   "title": "Total Return",
   "type": "singlestat",
   "description": "Total percentage return on the initial effective stake of active local validators. Excess deposits will be reflected as earnings.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 11 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(validator_balance{}) - (count(validator_balance{} > 16 and validator_statuses{} == 3)*32))/(count(validator_balance{} > 16 and validator_statuses{} == 3)*32)  "
    }
   ]
  },
  {
   "title": "Validator Process Stats",
   "type": "table-old",
   "description": "validator stats by public key over the lifetime of the validator process ",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "label_replace(max by(pubkey) (validator_balance{}), \"pubkey_short\", \"$1\", \"pubkey\", \"(.{10}).*\") ",
     "legendFormat": "balance"
    },
    {
     "expr": "label_replace(max by(pubkey) (validator_successful_proposals{}), \"pubkey_short\", \"$1\", \"pubkey\", \"(.{10}).*\")  "
    },
    {
     "expr": "label_replace(max by(pubkey) (validator_successful_attestations{}), \"pubkey_short\", \"$1\", \"pubkey\", \"(.{10}).*\")  "
    },
    {
     "expr": "label_replace(max by(pubkey) (validator_successful_aggregations{}), \"pubkey_short\", \"$1\", \"pubkey\", \"(.{10}).*\") "
    },
    {
     "expr": "label_replace(max by(pubkey) (validator_failed_attestations{}), \"pubkey_short\", \"$1\", \"pubkey\", \"(.{10}).*\") "
    },
    {
     "expr": "label_replace(max by(pubkey) (validator_failed_aggregations{}), \"pubkey_short\", \"$1\", \"pubkey\", \"(.{10}).*\") "
    },
    {
     "expr": "label_replace(max by(pubkey) (validator_balance{}), \"pubkey\", \"$1\", \"pubkey_short\", \"(.{10}).*\") "
    }
   ]
  },
  {
   "title": "Ping",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{job=\"ping_google\"}",
     "legendFormat": "google"
    },
    {
     "expr": "probe_duration_seconds{job=\"ping_cloudflare\"}",
     "legendFormat": "cloudflare"
    },
    {
     "expr": "probe_duration_seconds{job=\"ping_centurylink\"}",
     "legendFormat": "centurylink"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "description": "Processor usage on the server",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"system\"}[5m])) or sum(irate(node_cpu{mode=\"system\"}[5m]))",
     "legendFormat": "system"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"user\"}[5m])) or sum(irate(node_cpu{mode=\"user\"}[5m]))",
     "legendFormat": "user"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"nice\"}[5m])) or sum(irate(node_cpu{mode=\"nice\"}[5m]))",
     "legendFormat": "nice"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"iowait\"}[5m])) or sum(irate(node_cpu{mode=\"iowait\"}[5m]))",
     "legendFormat": "iowait"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"steal\"}[5m])) or sum(irate(node_cpu{mode=\"steal\"}[5m]))",
     "legendFormat": "steal"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) or sum(irate(node_cpu{mode=\"idle\"}[5m]))",
     "legendFormat": "idle"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"irq\"}[5m])) or sum(irate(node_cpu{mode=\"irq\"}[5m]))",
     "legendFormat": "irq"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"softirq\"}[5m])) or sum(irate(node_cpu{mode=\"softirq\"}[5m]))",
     "legendFormat": "softirq"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"guest\"}[5m])) or sum(irate(node_cpu{mode=\"guest\"}[5m]))",
     "legendFormat": "guest"
    }
   ]
  },
  {
   "title": "ALERTS",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 23 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Monthly Earnings",
   "type": "singlestat",
   "description": "Increase in all local validator balances over the last month",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(validator_balance{}) - sum(validator_balance{} offset 30d != 0) - (32 * count(validator_balance{} > 16)) + (32 * count(validator_balance{} offset 30d > 16))"
    }
   ]
  },
  {
   "title": "Weekly Earnings",
   "type": "singlestat",
   "description": "Increase in all local validator balances over the last week",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(validator_balance{}) - sum(validator_balance{} offset 7d != 0) - (32 * count(validator_balance{} > 16)) + (32 * count(validator_balance{} offset 7d > 16))"
    }
   ]
  },
  {
   "title": "Daily Earnings",
   "type": "singlestat",
   "description": "Increase in all local validator balances over the last day",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(validator_balance{}) - sum(validator_balance{} offset 1d != 0) - (32 * count(validator_balance{} > 16)) + (32 * count(validator_balance{} offset 1d > 16))"
    }
   ]
  },
  {
   "title": "Hourly Earnings",
   "type": "singlestat",
   "description": "Increase in all local validator balances over the last hour",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(validator_balance{}) - sum(validator_balance{} offset 1h != 0) - (32 * count(validator_balance{} > 16)) + (32 * count(validator_balance{} offset 1h > 16))"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 5, "w": 12, "x": 0, "y": 24 } },
  {
   "title": "Monthly Return, Annualized",
   "type": "singlestat",
   "description": "Percentage increase in all local validator balances over the last month",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 26 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "((sum(validator_balance{}) - sum(validator_balance{} offset 30d != 0) - (32 * count(validator_balance{} > 16)) +\t(32 * count(validator_balance{} offset 30d > 16)))/(32 * avg_over_time(count(validator_balance{} > 16)[30d:]))) * (365/30)",
     "legendFormat": "annualized monthly return"
    }
   ]
  },
  {
   "title": "Weekly Return, Annualized",
   "type": "singlestat",
   "description": "Percentage increase in all local validator balances over the last week",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 26 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "((sum(validator_balance{}) - sum(validator_balance{} offset 7d != 0) - (32 * count(validator_balance{} > 16)) +\t(32 * count(validator_balance{} offset 7d > 16)))/(32 * avg_over_time(count(validator_balance{} > 16)[7d:]))) * (365/7)",
     "legendFormat": "annualized weekly return"
    }
   ]
  },
  {
   "title": "Daily Return, Annualized",
   "type": "singlestat",
   "description": "Percentage increase in all local validator balances over the last day",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 26 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "((sum(validator_balance{}) - sum(validator_balance{} offset 1d != 0) - (32 * count(validator_balance{} > 16)) +\t(32 * count(validator_balance{} offset 1d > 16)))/(32 * avg_over_time(count(validator_balance{} > 16)[1d:]))) * 365",
     "legendFormat": "annualized daily return"
    }
   ]
  },
  {
   "title": "Hourly Return, Annualized",
   "type": "singlestat",
   "description": "Percentage increase in all local validator balances over the last hour",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 26 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "((sum(validator_balance{}) - sum(validator_balance{} offset 1h != 0) - (32 * count(validator_balance{} > 16)) +\t(32 * count(validator_balance{} offset 1h > 16)))/(32 * avg_over_time(count(validator_balance{} > 16)[1h:]))) * 365 * 24",
     "legendFormat": "annualized hourly return"
    }
   ]
  }
 ]
}