{
 "title": "Prysm Dashboard",
 "tags": [ "Prysm" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Last processed slot",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "max(beacon_slot)" }
   ]
  },
  {
   "title": "Current epoch",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "max(beacon_slot) / 32", "legendFormat": "epoch" }
   ]
  },
  {
   "title": "Last justified epoch",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "floor(max(beacon_current_justified_epoch))",
     "legendFormat": "epoch"
    }
   ]
  },
  {
   "title": "Last prev justified epoch",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "floor(max(beacon_previous_justified_epoch))"
    }
   ]
  },
  {
   "title": "Last finalized epoch",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "floor(max(beacon_finalized_epoch))"
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_used_bytes{namespace=\"beacon-chain\",persistentvolumeclaim=~\"beacondb-beacon-chain.*\"})"
    }
   ]
  },
  {
   "title": "Active Validators",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(validator_count{state=\"Active\"})"
    }
   ]
  },
  {
   "title": "Prylabs Network Control",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "targets": [
    {
     "expr": "max(assigned_pk_count)/(max(validator_count{state=\"Active\"})+avg(validator_count{state=\"Pending\"}))"
    }
   ]
  },
  {
   "title": "Beacon Chain Node CPU/Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "decbytes", "label": "Mem" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"beacon\"}",
     "legendFormat": "Memory allocation"
    },
    {
     "expr": "irate(process_cpu_seconds_total{job=\"beacon\"}[5m])",
     "legendFormat": "CPU usage"
    }
   ]
  },
  {
   "title": "state latest slot",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "beacon_slot > 0", "legendFormat": "latest slot {{pod_name}}" },
    {
     "expr": "beacon_current_justified_epoch * 32 > 0",
     "legendFormat": "last justified {{pod_name}}"
    },
    {
     "expr": "beacon_finalized_epoch * 32 > 0",
     "legendFormat": "last finalized {{pod_name}}"
    }
   ]
  },
  {
   "title": "gRPC success rate (5 minutes)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{job=\"beacon\",grpc_code=\"OK\"}[5m])) by (grpc_method) / sum(rate(grpc_server_handled_total{job=\"beacon\"}[5m])) by (grpc_method)",
     "legendFormat": "{{grpc_method}}"
    }
   ]
  },
  {
   "title": "Epochs since ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(max(beacon_slot) / 32) - max(head_finalized_epoch)",
     "legendFormat": "finalized"
    },
    {
     "expr": "(max(beacon_slot) / 32) - max(beacon_current_justified_epoch)",
     "legendFormat": "current justified"
    },
    {
     "expr": "(max(beacon_slot) / 32) - max(beacon_previous_justified_epoch)",
     "legendFormat": "previous justified"
    }
   ]
  },
  {
   "title": "Go Routines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"beacon\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Max participation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(total_voted_target_balances) / avg(total_eligible_balances)",
     "legendFormat": "Participation"
    }
   ]
  },
  {
   "title": "Allocated cluster keys",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 22 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "max(allocated_pk_count)", "legendFormat": "Allocated" }
   ]
  },
  {
   "title": "Assigned cluster keys",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 22 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "max(assigned_pk_count)" }
   ]
  },
  {
   "title": "powchain cache",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "Blocks" }
   ],
   "targets": [
    { "expr": "avg(powchain_block_cache_size)", "legendFormat": "Cache size" },
    {
     "expr": "avg_over_time(powchain_block_cache_hit[1m])/ (avg_over_time(powchain_block_cache_miss[1m])+avg_over_time(powchain_block_cache_hit[1m]))",
     "legendFormat": "Cache hit ratio"
    }
   ]
  },
  {
   "title": "Persistent Storage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{namespace=\"beacon-chain\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Peer counts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(p2p_peer_count{state=~\"Connected|Connecting\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Validator Deposits",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "Deposits" }
   ],
   "targets": [
    {
     "expr": "powchain_valid_deposits_received",
     "legendFormat": "total deposits {{pod_name}}"
    },
    { "expr": "beacondb_pending_deposits", "legendFormat": "pending deposits {{pod_name}}" }
   ]
  },
  {
   "title": "Avg boltDB bucket sizes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(bolt_bucket_physical_leaf_pages_allocated_bytes + bolt_bucket_physical_branch_pages_allocated_bytes) by (bucket)",
     "legendFormat": "{{bucket}}"
    },
    {
     "expr": "avg(bolt_db_freelist_free_page_allocated_bytes)",
     "legendFormat": "Freelist"
    }
   ]
  }
 ]
}