{
 "title": "Prysm P2P Stats",
 "tags": [ "Prysm" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "version",
    "query": "go_info{component=\"beacon-chain\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Pubsub Messages Per Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "avg(rate(p2p_message_received_total{version=~\"${version:pipe}\"}[5m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Processing failures per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "avg(irate(p2p_message_failed_processing_total{version=~\"${version:pipe}\"}[5m])) by (topic)\n",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Message validation success rate (30m)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1-avg(topk(5, increase(p2p_message_failed_validation_total[30m]) / increase(p2p_message_received_total[30m])) by (topic)) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Attestation inclusion delay",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(increase(attestation_inclusion_delay_slots_bucket[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Expired Attestations per Hour",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(increase(expired_aggregated_atts_total[1h]))",
     "legendFormat": "Attestations"
    }
   ]
  },
  {
   "title": "P2P Peers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(sum(p2p_peer_count{version=~\"${version:pipe}\", state=~\"Connected|Connecting\"}) by (pod_name))",
     "legendFormat": "Max"
    },
    {
     "expr": "min(sum(p2p_peer_count{version=~\"${version:pipe}\", state=~\"Connected|Connecting\"}) by (pod_name))",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(sum(p2p_peer_count{version=~\"${version:pipe}\", state=~\"Connected|Connecting\"}) by (pod_name))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Average Pubsub Peers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(p2p_topic_peer_count{version=~\"${version:pipe}\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Relay Network Pressure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{namespace=\"beacon-chain\", pod_name=\"relay-0\"}[2m])) ",
     "legendFormat": "Sent"
    },
    {
     "expr": "sum (rate (container_network_receive_bytes_total{namespace=\"beacon-chain\", pod_name=\"relay-0\"}[2m])) ",
     "legendFormat": "Receive"
    }
   ]
  }
 ]
}