{
 "title": "Slasher",
 "tags": [ "prysm" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Highest Average Observed Slot",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(slasher_highest_observed_epoch)"
    }
   ]
  },
  {
   "title": "Lowest Average Observed Slot",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(slasher_lowest_observed_epoch)"
    }
   ]
  },
  {
   "title": "Average Latest Min Span Distance",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(latest_min_span_distance_observed)"
    }
   ]
  },
  {
   "title": "Average Latest Max Span Distance",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(latest_max_span_distance_observed)"
    }
   ]
  },
  {
   "title": "Slasher CPU Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "decbytes", "label": "Mem" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{component=\"slasher\"}",
     "legendFormat": "Memory allocation"
    },
    {
     "expr": "irate(process_cpu_seconds_total{component=\"slasher\"}[5m])",
     "legendFormat": "CPU usage"
    }
   ]
  },
  {
   "title": "Slasher Attestations Received Per Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(slasher_attestations_received_total[5m])"
    }
   ]
  },
  {
   "title": "Detected Slashing Offenses",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "double_proposals_detected_total"
    },
    {
     "expr": "surrounded_votes_detected_total"
    },
    {
     "expr": "surrounding_votes_detected_total"
    },
    {
     "expr": "double_proposals_detected_total"
    }
   ]
  },
  {
   "title": "Total Slashings Included in Blocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "attester_slashings_included_total"
    },
    {
     "expr": "proposer_slashings_included_total"
    }
   ]
  },
  {
   "title": "Slashing Reattempts Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "attester_slashing_reattempts_total"
    },
    {
     "expr": "proposer_slashing_reattempts_total"
    }
   ]
  },
  {
   "title": "Attester Slashings Submitted to Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_client_handled_total{grpc_method=\"SubmitAttesterSlashing\"}"
    }
   ]
  },
  {
   "title": "Slashings Failed Sig Verify Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pending_attester_slashing_fail_sig_verify_total"
    },
    {
     "expr": "pending_proposer_slashing_fail_sig_verify_total"
    }
   ]
  },
  {
   "title": "Slasher Epoch Spans Cache Hit/Miss",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(epoch_spans_cache_hit[1m])/ (avg_over_time(epoch_spans_cache_miss[1m])+avg_over_time(epoch_spans_cache_hit[1m]))"
    },
    { "expr": "epochsp" }
   ]
  },
  {
   "title": "Slasher Highest and Lowest Observed Epoch",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "slasher_highest_observed_epoch" },
    { "expr": "slasher_lowest_observed_epoch" }
   ]
  },
  {
   "title": "Pending Slashings in Pool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "num_pending_attester_slashings" },
    { "expr": "num_pending_proposer_slashings" }
   ]
  },
  {
   "title": "Latest Min/Max Span Distances Observed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "latest_max_span_distance_observed"
    },
    {
     "expr": "latest_min_span_distance_observed"
    }
   ]
  },
  {
   "title": "Slasher Epoch Spans Cache Evictions Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "epoch_spans_cache_evictions_total"
    }
   ]
  }
 ]
}