{
 "title": "Nimbus Libp2p",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "container",
    "query": "label_values(process_virtual_memory_bytes{job=\"beacon-node-metrics\"},container)"
   },
   {
    "name": "instance",
    "query": "label_values(process_virtual_memory_bytes{job=\"beacon-node-metrics\"},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "resources #${container}@${instance}",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"beacon-node-metrics\",container=\"${container}\",instance=\"${instance}\"}[2m]) * 100",
     "legendFormat": "CPU usage %"
    },
    {
     "expr": "process_open_fds{job=\"beacon-node-metrics\",container=\"${container}\",instance=\"${instance}\"}",
     "legendFormat": "open file descriptors"
    },
    {
     "expr": "process_resident_memory_bytes{job=\"beacon-node-metrics\",container=\"${container}\",instance=\"${instance}\"}",
     "legendFormat": "RSS"
    },
    {
     "expr": "nim_gc_mem_bytes{job=\"beacon-node-metrics\",container=\"${container}\",instance=\"${instance}\"}",
     "legendFormat": "Nim GC mem total"
    },
    {
     "expr": "nim_gc_mem_occupied_bytes{job=\"beacon-node-metrics\",container=\"${container}\",instance=\"${instance}\"}",
     "legendFormat": "Nim GC mem used"
    }
   ]
  },
  {
   "title": "libp2p open streams #${container}@${instance}",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(type) (libp2p_open_streams{job=\"beacon-node-metrics\",container=\"${container}\",instance=\"${instance}\"})",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum (libp2p_open_streams{job=\"beacon-node-metrics\",container=\"${container}\",instance=\"${instance}\"})",
     "legendFormat": "combined"
    }
   ]
  },
  {
   "title": "libp2p mplex channels #${container}@${instance}",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(initiator,node)(libp2p_mplex_channels{job=\"beacon-node-metrics\",container=\"${container}\",instance=\"${instance}\"})",
     "legendFormat": "initiator {{initiator}}"
    },
    {
     "expr": "sum(libp2p_mplex_channels{job=\"beacon-node-metrics\",container=\"${container}\",instance=\"${instance}\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "GC heap objects #${container}@${instance}",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nim_gc_heap_instance_occupied_bytes{job=\"beacon-node-metrics\",container=\"${container}\",instance=\"${instance}\"}",
     "legendFormat": "{{type_name}}"
    }
   ]
  },
  {
   "title": "libp2p mplex channels per peer #${container}@${instance}",
   "type": "graph",
   "gridPos": { "h": 15, "w": 10, "x": 14, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by(peer, initiator)(libp2p_mplex_channels{job=\"beacon-node-metrics\",container=\"${container}\",instance=\"${instance}\"}))",
     "legendFormat": "peer {{peer}}"
    }
   ]
  },
  {
   "title": "SQLite3 #${container}@${instance}",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sqlite3_memory_used_bytes{job=\"beacon-node-metrics\",container=\"${container}\",instance=\"${instance}\"}",
     "legendFormat": "Memory used"
    }
   ]
  },
  {
   "title": "blocks #${container}@${instance}",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceil(rate(beacon_blocks_received_total{job=\"beacon-node-metrics\",container=\"${container}\",instance=\"${instance}\"}[2m]))",
     "legendFormat": "received"
    },
    {
     "expr": "ceil(rate(beacon_blocks_proposed_total{job=\"beacon-node-metrics\",container=\"${container}\",instance=\"${instance}\"}[2m]))",
     "legendFormat": "proposed"
    }
   ]
  },
  {
   "title": "libp2p peers #${container}@${instance}",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(type) (libp2p_peers{job=\"beacon-node-metrics\",container=\"${container}\",instance=\"${instance}\"})",
     "legendFormat": "connected peers"
    },
    {
     "expr": "sum (libp2p_pubsub_peers{job=\"beacon-node-metrics\",container=\"${container}\",instance=\"${instance}\"})",
     "legendFormat": "pubsub peers"
    }
   ]
  },
  {
   "title": "attestations #${container}@${instance}",
   "type": "graph",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(increase(beacon_attestations_received_total{job=\"beacon-node-metrics\",container=\"${container}\",instance=\"${instance}\"}[2m]))",
     "legendFormat": "received"
    },
    {
     "expr": "round(increase(beacon_attestations_sent_total{job=\"beacon-node-metrics\",container=\"${container}\",instance=\"${instance}\"}[2m]))",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "validators #${container}@${instance}",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "beacon_current_validators{job=\"beacon-node-metrics\",container=\"${container}\",instance=\"${instance}\"}",
     "legendFormat": "current validators"
    },
    {
     "expr": "beacon_current_live_validators{job=\"beacon-node-metrics\",container=\"${container}\",instance=\"${instance}\"}",
     "legendFormat": "current live validators"
    }
   ]
  },
  {
   "title": "received attestation delay (s) #${container}@${instance}",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "round(increase(beacon_attestation_received_seconds_from_slot_start_bucket{job=\"beacon-node-metrics\",container=\"${container}\",instance=\"${instance}\"}[2m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "pool.cachedStates #${container}@${instance}",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 35 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "beacon_state_data_cache_hits_total{job=\"beacon-node-metrics\",container=\"${container}\",instance=\"${instance}\"} * 100 / (beacon_state_data_cache_hits_total{job=\"beacon-node-metrics\",container=\"${container}\",instance=\"${instance}\"} + beacon_state_data_cache_misses_total{job=\"beacon-node-metrics\",container=\"${container}\",instance=\"${instance}\"})",
     "legendFormat": "cache hit rate"
    }
   ]
  },
  {
   "title": "libp2p received gossip #${container}@${instance}",
   "type": "heatmap",
   "gridPos": { "h": 16, "w": 14, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "round(sum by (topic) (increase(libp2p_pubsub_received_messages_total{job=\"beacon-node-metrics\",container=\"${container}\",instance=\"${instance}\"}[2m])))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "RSS mem #${container}@${instance}",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 40 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"beacon-node-metrics\",container=\"${container}\",instance=\"${instance}\"}"
    }
   ]
  },
  {
   "title": "CPU usage #${container}@${instance}",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 40 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"beacon-node-metrics\",container=\"${container}\",instance=\"${instance}\"}[2m]) * 100"
    }
   ]
  },
  {
   "title": "current slot #${container}@${instance}",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 42 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "beacon_slot{job=\"beacon-node-metrics\",container=\"${container}\",instance=\"${instance}\"}"
    }
   ]
  },
  {
   "title": "att'ns sent #all",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 17, "y": 42 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(beacon_attestations_sent_total{job=\"beacon-node-metrics\",container=~\"beacon-node-testnet1-.\"})"
    }
   ]
  },
  {
   "title": "att'ns recv'd #${container}@${instance}",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 42 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "beacon_attestations_received_total{job=\"beacon-node-metrics\",container=\"${container}\",instance=\"${instance}\"}"
    }
   ]
  },
  {
   "title": "current epoch #${container}@${instance}",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 44 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "beacon_current_epoch{job=\"beacon-node-metrics\",container=\"${container}\",instance=\"${instance}\"}"
    }
   ]
  },
  {
   "title": "current justified epoch #${container}@${instance}",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 17, "y": 44 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "beacon_current_justified_epoch{job=\"beacon-node-metrics\",container=\"${container}\",instance=\"${instance}\"}"
    }
   ]
  },
  {
   "title": "runtime #${container}@${instance}",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 44 },
   "format": "dthms",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"beacon-node-metrics\",container=\"${container}\",instance=\"${instance}\"}"
    }
   ]
  },
  {
   "title": "peers #${container}@${instance}",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 46 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "libp2p_peers{job=\"beacon-node-metrics\",container=\"${container}\",instance=\"${instance}\"}"
    }
   ]
  },
  {
   "title": "last finalized epoch #${container}@${instance}",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 17, "y": 46 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "beacon_finalized_epoch{job=\"beacon-node-metrics\",container=\"${container}\",instance=\"${instance}\"}"
    }
   ]
  },
  {
   "title": "libp2p sent gossip #${container}@${instance}",
   "type": "heatmap",
   "gridPos": { "h": 17, "w": 14, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "round(sum by (topic) (increase(libp2p_pubsub_sent_messages_total{job=\"beacon-node-metrics\",container=\"${container}\",instance=\"${instance}\"}[2m])))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "libp2p published messages per topic #${container}@${instance}",
   "type": "heatmap",
   "gridPos": { "h": 16, "w": 14, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "sum by (topic) (increase(libp2p_pubsub_messages_published_total{job=\"beacon-node-metrics\",container=\"${container}\",instance=\"${instance}\"}[2m]))",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}