{
 "title": "Nimbus Metrics",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Attestations Received",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_attestations_received_total[1h])*3600",
     "legendFormat": "{{container}}@{{instance}}"
    }
   ]
  },
  {
   "title": "Attestations Sent",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_attestations_sent_total[1h])*3600",
     "legendFormat": "{{container}}@{{instance}}"
    }
   ]
  },
  {
   "title": "Blocks Proposed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "beacon_blocks_proposed_total", "legendFormat": "{{container}}@{{instance}}" }
   ]
  },
  {
   "title": "Blocks Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_blocks_received_total[1h])",
     "legendFormat": "{{container}}@{{instance}}"
    }
   ]
  },
  {
   "title": "Beacon Slots Created (rate 1h)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(beacon_slot_created[1h])", "legendFormat": "{{container}}@{{instance}}" }
   ]
  },
  {
   "title": "Beacon Slots (rate 1h)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(beacon_slot[1h])", "legendFormat": "{{container}}@{{instance}}" }
   ]
  }
 ]
}